### ISSUE TITLE
Why does running data_process show the following error

### ISSUE THREAD

**Issue by baosir529a** [BaoSir529/dual-encoder4aste#1]
Traceback (most recent call last):
  File "E:\PyCharm\代码项目\dual-encoder4aste-main\dual-encoder4aste-main\data\v1_data_process.py", line 3, in <module>
    import spacy
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\__init__.py", line 13, in <module>
    from . import pipeline  # noqa: F401
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\pipeline\attributeruler.py", line 8, in <module>
    from ..language import Language
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\language.py", line 42, in <module>
    from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\pipe_analysis.py", line 6, in <module>
    from .tokens import Doc, Span, Token
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from ._serialize import DocBin
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\tokens\_serialize.py", line 14, in <module>
    from ..vocab import Vocab
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "spacy\tokens\doc.pyx", line 49, in init spacy.tokens.doc
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\site-packages\spacy\schemas.py", line 272, in <module>
    class TokenPattern(BaseModel):
  File "pydantic\main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 411, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 342, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 451, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 545, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 550, in pydantic.fields.ModelField._type_analysis
  File "E:\Anaconda\Anaconda\envs\dualencoder\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

**Comment by dfasd1** [comment]
你好，请问你解决了吗

**Comment by ghyhj** [comment]
you don't have to run it, it's already in the original file, just skip it
